name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Suma Test
      id: suma-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Suma Test
        setup-command: mvn compile
        command: mvn test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SUMA-TEST_RESULTS: "${{steps.suma-test.outputs.result}}"
      with:
        runners: suma-test
